[package]
name = "chrome_profile_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.2"
serde_json = "1.0"
registry = "*"
utfx = "*"
winapi = "*"
clap = { version = "4.1.4", features = ["derive"] }