name: Deploy MSI

on:
  repository_dispatch:
    types: [build_success]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  runs-on: ubuntu-latest
  steps:

  - uses: actions/checkout@v3
    with:
      ref: ${{ github.event.client_payload.sha }}
  - name: Set up cargo cache
    uses: actions/cache/restore@v3
    continue-on-error: false
    with:
      path: |
        target/
      key: windows-target-${{ hashFiles('**/Cargo.lock') }}
      restore-keys: windows-target-

  - name: copy file via ssh password
    uses: appleboy/scp-action@master
    with:
      host: ${{ secrets.SIRSONIC_HOST }}
      username: ${{ secrets.SIRSONIC_USER }}
      key: ${{ secrets.SIRSONIC_KEY }}
      port: ${{ secrets.SIRSONIC_PORT }}
      source: "target/wix/chrome_valet-${{ github.event.client_payload.cv_version }}-x86_64.msi"
      target: "dl.sirsonic.com/releases/chrome_valet"
      strip_components: 3
