name: Deploy MSI

on:
  workflow_dispatch:
    inputs:
        cv_version:
          description: 'Chrome Valet version'
          required: true
          default: '0.0.0'
  
env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.CV_WORKFLOW_TOKEN}}
          workflow: rust.yml
          name: "chrome_valet-${{ github.event.inputs.cv_version }}-x86_64.msi"

      - name: ls directory
        run: |
          ls -l

      - name: Check chrome_valet-${{ github.event.inputs.cv_version }} existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "chrome_valet-${{ github.event.inputs.cv_version }}-x86_64.msi"

      - if: github.event.inputs.cv_version != '0.0.0' && steps.check_files.outputs.files_exists == 'true'
        name: scp chrome_valet-${{ github.event.inputs.cv_version }} to release destination
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SIRSONIC_HOST }}
          username: ${{ secrets.SIRSONIC_USER }}
          key: ${{ secrets.SIRSONIC_KEY }}
          port: ${{ secrets.SIRSONIC_PORT }}
          source: "chrome_valet-${{ github.event.inputs.cv_version }}-x86_64.msi"
          target: "dl.sirsonic.com/releases/chrome_valet"
          overwrite: true
