name: Testing Workflow
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Install wsl
      uses: Vampire/setup-wsl@v2
      with:
          use-cache: 'true'   
          additional-packages: ssh
    
    - name: scp msi to sirsonic.com
      shell: wsl-bash {0}
      run: echo '$SIRSONIC_KEY' > priv_key
      env:
        SIRSONIC_KEY: '${{secrets.SIRSONIC_KEY}}'
        
    - name: scp msi to sirsonic.com
      shell: wsl-bash {0}
      run: chmod 600 priv_key
      
    - name: scp msi to sirsonic.com
      shell: wsl-bash {0}
      run: echo testfile > foobar
      
    - name: scp msi to sirsonic.com
      shell: wsl-bash {0}
      run: scp -i priv_key -o PasswordAuthentication=no "foobar" gthomson@sirsonic.com:dl.sirsonic.com/releases/chrome_valet/

