name: Testing Workflow
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        enableCrossOsArchive: true
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          !target/wix
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SIRSONIC_HOST }}
        username: ${{ secrets.SIRSONIC_USER }}
        key: ${{ secrets.SIRSONIC_KEY }}
        port: ${{ secrets.SIRSONIC_PORT }}
        source: "target/wix/chrome_valet-0.1.1-x86_64.msi"
        target: "dl.sirsonic.com/releases/chrome_valet"
      
   
